version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "rh"
    ports:
      - 3308:3306
  app:
    build: .
    command: bash -c "sleep 30 && ./node_modules/.bin/sequelize db:migrate && ./node_modules/.bin/sequelize db:seed:all && npm run dev"
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

